tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'

brew 'ag'
brew 'autojump'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'cowsay'
brew 'ctags'
brew 'figlet'
brew 'ghc'
brew 'git'
brew 'gnu-sed'
brew 'gnupg2', args: ['with-readline']
brew 'groovy'
brew 'gtypist'
brew 'leiningen'
brew 'lua'
brew 'luajit'
brew 'maven'
brew 'neovim'
brew 'node'
brew 'pv'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby'
brew 'shellcheck'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-client-server', 'with-lua', 'with-luajit', 'with-python3']

# GNU utils to replace BSD findutils
tap 'homebrew/dupes'
brew 'grep', args: ['with-default-names']
brew 'findutils', args: ['with-default-names']

# Cask
cask 'anki'
cask 'ccmenu'
cask 'dash'
cask 'dropbox'
cask 'iterm2'
cask 'java'
cask 'macvim'
cask 'omnioutliner'
cask '1password'
cask 'rescuetime'
cask 'selfcontrol'
cask 'sequel-pro'
cask 'slack'
cask 'spotify'
cask 'font-fira-mono'
cask 'font-fira-code'
