tap 'homebrew/bundle'
# tap 'homebrew/cask'
# tap 'homebrew/cask-fonts'

brew 'ag'
brew 'autojump'
brew 'babashka'
brew 'bash'
brew 'bash-completion@2'
brew 'coreutils'
brew 'cowsay'
brew 'figlet'
brew 'ghc'
brew 'git'
brew 'gnu-sed'
brew 'gnupg2'
brew 'groovy'
brew 'gtypist'
brew 'jq'
brew 'leiningen'
brew 'lua'
brew 'luajit'
brew 'maven'
brew 'neovim'
brew 'node'
brew 'pv'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby'
brew 'shellcheck'
brew 'terminal-notifier'
brew 'tmux'
brew 'tree'
brew 'universal-ctags'
brew 'vim'

# GNU utils to replace BSD findutils
brew 'grep'
brew 'findutils'

# Cask
# cask 'anki'
# cask 'ccmenu'
# cask 'dash'
# cask 'dropbox'
# cask 'java'
# cask 'iterm2'
# cask 'macvim'
# cask 'omnioutliner'
# cask 'selfcontrol'
# cask 'tableplus'
# cask 'font-fira-mono'
# cask 'font-fira-code'
