#!/usr/bin/env bash

# cd to dotfiles directory
cd "$(dirname "$BASH_SOURCE")"
BASE=$(pwd)

# link RC files
mkdir -pv bak
for rc in *rc *aliases *profile *ignore *config tmux.conf ctags; do
    [ -e ~/."$rc" ] && mv -v ~/."$rc" bak/."$rc"
    ln -sfv "$BASE/$rc" ~/."$rc"
done

# link config directories
for dir in $(find ./* -maxdepth 0 -type d); do
    ln -sfv "$BASE/$dir" ~/."$dir"
done

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
    curl https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh \
        -o ~/.git-prompt.sh
fi

# FZF
git clone https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# OS X
if [ "$(uname -s)" = 'Darwin' ]; then
    # Homebrew
    [ -z "$(which brew)" ] &&
        ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/install/master/install)"
    brew update
    brew install \
        ag bash bash-completion coreutils ctags fasd gibo git ghi \
        libgit2 leiningen lua luajit macvim maven python python3 pv \
        reattach-to-user-namespace ruby shellcheck tmux tree vim wget
    # GNU utils to replace BSD findutils
    brew tap homebrew/dupes
    brew install grep --with-default-names
    brew install findutils --with-default-names
    # Neovim
    brew tap neovim/homebrew-neovim
    brew install --HEAD neovim
    pip install neovim
fi

tmux source-file ~/.tmux.conf
