#!/usr/bin/env bash

alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias ssh='TERM=xterm ssh -F "${XDG_CONFIG_HOME}/ssh/config"'
alias ls='ls -hFG --color=auto'
alias ll='ls -hlFG --color=auto'
alias recent='find * -type f -mtime 0'
alias gtypist='gtypist -b -e1 -w -S'
alias jconsole='_JAVA_OPTIONS="" jconsole'
alias testping='ping -c3 www.google.com'
alias initvim='nvim -c "call fugitive#detect(expand(\"%:p\"))" "$XDG_CONFIG_HOME/nvim/init.vim"'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

if [[ $(uname -s) = 'Darwin' ]]; then
    alias vim='mvim -v'
fi

# git aliases
alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gae='git add -e'
alias gb='git branch --color'
alias gci='git commit'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcp='git cherry-pick'
alias gd='git diff --color'
alias gdc='git diff --cached --color'
alias ggo='git log --graph --color'
alias gh='git help'
alias gm='git merge'
alias gmff='git merge --ff-only'
alias gmnf='git merge --no-ff'
alias gpo='git push --set-upstream origin `git rev-parse --abbrev-ref HEAD`'
alias gpb='git push --set-upstream --force-with-lease origin `git rev-parse --abbrev-ref HEAD`'
alias gpr='git pull --rebase'
alias grm='git rebase master'
alias grc='git rebase --continue'
alias gro='git fetch; git rebase origin/master'
alias fixup='git rebase -i `git merge-base master HEAD`'
alias gst='git status --short --branch'
alias gsh='git show HEAD'
alias gss='git stash save'
alias gsp='git stash pop'
alias gsl='git stash list'
alias restore='git checkout -; git stash pop'

if [[ $(uname -s) = Darwin ]]; then
    alias locate='mdfind -name'
fi

[ -f ~/.bash_aliases.local ] && source ~/.bash_aliases.local
