#!/usr/bin/env bash

INSTALL_DIR=$(cd "$(dirname "$0")" && pwd)
BASE=$(dirname "$INSTALL_DIR")

if [[ -z $XDG_CONFIG_HOME || -z $XDG_CACHE_HOME || -z $XDG_DATA_HOME ]]; then
    echo 'XDG environment variables not set. Aborting...';
    exit 1;
fi

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CACHE_HOME"
mkdir -p "$XDG_DATA_HOME"

if command -v tic; then
    echo 'Installing terminfo profiles...'
    for terminfo in $BASE/tweaked_terminfos/*; do
        tic "$terminfo"
    done
    echo 'Done.'
else
    echo 'WARNING: tic command not found. Skipping terminfo installation...'
fi
echo

echo 'Installing packages...'
# git-prompt
if [[ ! -e $XDG_DATA_HOME/git-prompt.sh ]]; then
    curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
        -o "$XDG_DATA_HOME/git-prompt.sh"
fi

# FZF
echo 'Installing FZF...'
git clone https://github.com/junegunn/fzf.git "$XDG_DATA_HOME/fzf"
"$XDG_DATA_HOME/fzf/install" --all --no-update-rc
mv ~/.fzf.bash "$XDG_DATA_HOME/fzf/fzf.bash"
mv ~/.fzf.zsh "$XDG_DATA_HOME/fzf/fzf.zsh"
echo 'Done installing FZF.'

# MacOS
if [[ $(uname -s) = 'Darwin' ]]; then
    # RVM
    curl -L https://get.rvm.io | bash -s stable
    rvm use ruby --install --default
    # Homebrew
    while ! command -v brew &>/dev/null; do
        echo "Please install Homebrew (https://raw.github.com/Homebrew/install/master/install) to ${HOMEBREW_HOME}"
        read -r -p 'Press Enter to continue...'
    done

    echo 'Installing homebrew packages...'
    brew update; brew bundle
    echo 'Done installing homebrew packages.'

    if command -v pip2; then
        pip2 install --user neovim
    fi
    if command -v pip3; then
        pip3 install --user neovim flake8 csvkit
    else
        echo "WARNING: pip3 command not found. Skipping installation..."
    fi
    if command -v gem; then
        gem install pry rdoc rdoc-data rubocop
    else
        echo "WARNING: gem command not found. Skipping installation..."
    fi

    # Vim-Plug
    sh -c 'curl -fLo "${XDG_CONFIG_HOME}"/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    if command -v nvim; then
        nvim +PlugInstall +qall
    else
        echo "WARNING: nvim command not found. Skipping Vim-Plug installation..."
    fi
fi
